HabanaAI/optimum-habana-fork

optimum/habana/transformers/training_args.py
Cleanup code in training_args.py to remove setting of PT_HPU_LAZY_MODE=2 (this is not supported SynapseAI release 1.13.0 onwards).
=> Remove setting of PT_HPU_LAZY_MODE=2 in training_args.py

examples/stable-diffusion/plot_loss_curve.py, examples/stable-diffusion/run.sh, examples/stable-diffusion/run_1x_bs16.sh, examples/stable-diffusion/train_text_to_image_sdxl.py
=> STDXL ft changes

examples/language-modeling/run_lora_clm.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py
Exposes FusedRoPE enable/disable for Llama model from task scripts (currently done for only run_lora_clm.py). It is useful to have this capability for debugging purposes.  Immediate motivation is to use this as a workaround for issue we see with FusedRoPE in compile mode.
=> Expose Llama Fused OPs control from run_lora_clm.py

examples/text-generation/README.md, examples/text-generation/run_generation.py, examples/text-generation/utils.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
To enhance throughput in scenarios with long new tokens, break down the KV cache into multiples of the bucket width. Use this to compute attention rather than using the entire KV cache. 
Add `--bucket_size=128 --bucket_internal` to the commands to enable the feature.
=> enable internal kv bucket in llama

examples/language-modeling/README.md, examples/language-modeling/run_lora_clm.py, examples/text-generation/README.md, examples/text-generation/run_generation.py, examples/text-generation/utils.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py, optimum/habana/transformers/trainer.py
This is a follow-up on: https://github.com/huggingface/optimum-habana/pull/623
where main issue is that when running with Flash Attention in causal mode (required for performance and memory optimizations on 1st token) it will generate a triangular attention mask - same on each batch of the input data.
If we have more than one batch of sequences that have different lengths, tokenizer will include a padding for those sentences that have smaller sequence lengths than 'max input tokens'. In the case of Flash Attention in causal mode, where triangular attention mask is applied to all the inputs, this will effectively mean that padding tokens are also attended to, which will in turn result in junk output being generated
This PR propagates the modes of running to run_generation.py so that …
=> Enable Flash Attention in recompute and causal modes

optimum/habana/checkpoint_utils.py, optimum/habana/transformers/generation/utils.py
1 The current code can load only .bin or .pt whereas Falcon-180B ckpt files are in .safetensors format. This change enabled loading ckpt files in .safetensor format
2 The ValueError "The following `model_kwargs` are not used by the model: ['token_type_ids'] )" is addressed by introducing a workaround that removes ‘token_type_ids’ from the model_kwargs.
=> enable falcon-180b inference

optimum/habana/transformers/trainer.py
'mark_step()' should not be called for eager mode so conditionally skipped for lazy mode.
=> Fixing LLAMA-V2-70B-FT-HF (8x) issue for eager mode

optimum/habana/checkpoint_utils.py
Reopening #19 because #15 does not work for TinyLlama/TinyLlama-1.1B-Chat-v1.0. This model does not have the checkpoint index files.
```
ValueError: Can't find a checkpoint index (pytorch_model.bin.index.json or model.safetensors.index.json) in /root/.cache/huggingface/hub/models--TinyLlama--TinyLlama-1.1B-Chat-v1.0/snapshots/77e23968eed12d195bd46c519aa679cc22a27ddc.
```
The [TinyLlama model](https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0) only has checkpoints in the form of `model.safetensors`. This checkpoint needs to be included in the list of checkpoints that is passed to DeepSpeed in order for the model to function properly when initialized with DeepSpeed.
This PR adds the safetensor checkpoints to the list of checkpoints passed to DeepSpeed.
**Note**: This change requires …
=> add support for TinyLlama model

examples/stable-diffusion/run_1x_bs16.sh, examples/stable-diffusion/train_text_to_image_sdxl.py, optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
Following changes:
1. Added hpu graph for training, and disable it due to OOM.
2. changed resolution to 1024, 
3. changed dataloader_num_process to 8
4. Changed the noise scheduler to DDPM for accuracy.
=> stdxl optimizations 

optimum/habana/checkpoint_utils.py, optimum/habana/transformers/generation/utils.py
PR#15 reads a set of ckpt file names from the index json file.
When OH downloads files from the hub instead of loading from a cache dir, get_repo_root() skips downloading the index json file. Thus the PR#15 fails to load file names.
This PR scans the path and returns a list of names that matches the pattern
Tested the models in cache dir:
Falcon-7b, Falcon-40b, Falcon-180b, Llama-70b
Tested the models downloaded from HF hub:
Falcon-7b, Falcon-40b, TinyLlama
=> Update ckpt loading

optimum/habana/transformers/generation/utils.py
=> Fix tests (#669)

examples/text-generation/run_generation.py, examples/text-generation/run_lm_eval.py, examples/text-generation/utils.py
Add disk_offload flag that controls device_map=auto. Setting this flag enbales weights offload to disk when cpu memory runs OOM.
Add const serialization path flag that gets a path for where to serialize const sections, so if there is no space on device to save all const sections they will be offloaded to disk.
=> Enable Llama2 70B to run with hqt on single card

optimum/habana/transformers/models/llama/modeling_llama.py
Fixes accuracy for Llama fine-tuning & LLama inference seen with PyTorch 2.2 builds
=> Set _use_sdpa to False to disable torch sdpa

optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
Mark step helping in reducing workspace memory by
approx twice of (BS,seq len, hidden dim).
Inplace add helping in reducing persistent tensors by 
approx twice of (BS, seq len, hidden dim).
=> Add mark step and inplace residual add in llama model code to reduce memory consumption

optimum/habana/transformers/generation/utils.py
Extend function #24 to sample mode.
The command to reproduce performance is as follows:
`python ../gaudi_spawn.py --use_deepspeed --world_size 4 run_generation.py --model_name_or_path meta-llama/Llama-2-70b-hf --use_hpu_graphs --use_kv_cache --max_input_tokens 128 --max_new_tokens 2048 --batch_size 240 --attn_softmax_bf16  --trim_logits --bf16 --reuse_cache --warmup 1 --n_iterations 1 --limit_hpu_graphs --do_sample --bucket_size 256 --bucket_internal`
=> extend bucket_internal to SAMPLE generation mode

examples/text-generation/README.md, examples/text-generation/run_generation.py, examples/text-generation/utils.py
Disable SDPA attention until gpt-bigcode model support FusedSDPA attention.
=> Disable SDPA Attention for gpt-bigcode model

optimum/habana/transformers/models/llama/modeling_llama.py
Training script uses dynamic control flow based on the success of a module import, which caused a graph break.
This patch handles the control flow through boolean flags which avoids graph breaks due to module import.
=> Fix graph breaks in LLama-FT torch compile mode execution

examples/text-generation/quantization_config/maxabs_measure_include_ouputs.json
by default the habana-quantization-toolkit exclude output tensor scale measurements for quantization
added a json config example of how to enable the measurements of the output tensors.
=> add quantization config example including measure of output tensors

optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/__init__.py, optimum/habana/transformers/models/swin/__init__.py, optimum/habana/transformers/models/swin/modeling_swin.py
In certain 1x systems , we notice a drop in performance for swin models as get_attn_mask gets executed in cpu instead of hpu. This was seen after pytorch upgrade to 2.2
This fix allows img_mask in get_attn_mask() to be moved back hpu.
=> move img_mask@get_attn_mask() to hpu

optimum/habana/transformers/models/llama/modeling_llama.py
Added additional check to run with distributed enabled and  world_size=1 (#96)
* Added additional check to run with distributed enabled and  world_size = 1
* Reduce the number of graph splits to avoid memory allocation error  for 1x LLAMA1_7b_ft
=> Added additional check to run with distributed enabled and  world_size=1 (#96)

optimum/habana/transformers/synapse_profiler_api.py, optimum/habana/transformers/trainer.py, optimum/habana/transformers/training_args.py
Add training args to capture device profiling traces
=> Add training args to capture device profiling traces

optimum/habana/transformers/models/llama/modeling_llama.py
Add mark_step only for inference to split the graphs so that it fits in memory
=> Add mark_step only for inference

examples/text-generation/run_lm_eval.py, tests/test_text_generation_example.py
Cherry-picked change from habana-main branch.
=> add falcon180b FP8 test (#104)

examples/text-generation/utils.py, optimum/habana/transformers/models/falcon/modeling_falcon.py
This PR fixes the below error from run_lm_eval.py
RuntimeError: Output 0 of torch::autograd::CppNode is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to
handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can fix this by cloning the output of the custom Function.
=> Fix for view+inplace error from Falcon 

examples/text-generation/run_lm_eval.py, optimum/habana/transformers/models/llama/modeling_llama.py
* Done to allow quantization using HQT
* Added use_flash_attention and flash_attention_recompute to run_lm_eval
=> Encapsulate FSDPA in GaudiLlamaAttention

optimum/habana/transformers/trainer_utils.py
This is the cherry-pick of the Optimum-habana commit https://github.com/huggingface/optimum-habana/pull/769. The fix consists in extracting the dtype of the first logit tensor and set it as the target dtype. We used to extract the dtypes of all logit tensors, leading to nested tuples that led to this issue. There is no reason for logits to have different dtypes, so we can simplify the dtype extraction logic.
Fixes # (https://github.com/huggingface/optimum-habana/issues/754)
=> Fix get_dtype and convert_into_dtypes (#769)

examples/text-generation/utils.py, optimum/habana/accelerate/utils/dataclasses.py, tests/test_fsdp_examples.py
The new backend has been introduced to pytorch-integraton - HPU_BACKEND . The deprecated backend ( AOT_HPU_TRAINING_BACKEND ) shall no longer be available in optimum habana as it's going to be removed from pytorch-integration.
=> Remove deprecated AOT_HPU_TRAINING_BACKEND

optimum/habana/transformers/models/llama/modeling_llama.py
When passing --bf16 to train/inference cmd, ensure all input tensors are cast to bf16. 
Change fused rope input type to bf16 for llama models
=> set all fusedrope inputs to bf16

examples/text-generation/utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/modeling_utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
Pad KV cache to full input + new tokens len for decode phase. Delete the KV cache used as inputs by HPU graphs after full prompt generation. Ensure KV cache is not returned as output tensor during decode phase. Deletion of KV cache input tensor used by HPU graphs needs to be protected by PT_HPUGRAPH_DISABLE_TENSOR_CACHE env variable.
All the changes are protected by bucket internal flag.
=> Use KV cache till input seq len for prefill phase

optimum/habana/transformers/models/mistral/modeling_mistral.py
=> Add marksteps to optimize mistral text generation performance

optimum/habana/transformers/models/mistral/modeling_mistral.py
Adds fusedrope optimization to mistral
=> add fused rope optimization to mistral model

optimum/habana/transformers/generation/utils.py
=> Sampling search UseKV cache till input seq len for prefill phase

examples/text-generation/run_lm_eval.py
Backward backend was incorrectly launched because torch.nograd was missing
=> Add nograd() to prevent backward backend

examples/summarization/ds_flan_t5_z3_config_bf16.json
This PR changes the deepspeed config of summarization models to
run with "reduce_scatter" : false by default.
FlanT5 performance issue where the 8x performance drops to 5% when ran with deepspeed.
=> [SW-12028] - set ds config "reduce scatter" to false

examples/text-generation/evaluation.py, examples/text-generation/requirements_lm_eval.txt, examples/text-generation/run_generation.py
use rouge metric to evaluate the correctness of the model, it uses openorca dataset
=> Add rouge metric evalution for llama 70B with orca datasets

optimum/habana/accelerate/utils/transformer_engine.py
Only Non-trainable linear layers are converted to FP8 precision
=> Run trainable linear layers in BF16

examples/text-generation/README.md, examples/text-generation/run_lm_eval.py, optimum/habana/transformers/models/mistral/modeling_mistral.py
Add support for Mistral fp8 text-generation. 
Porting from: 
https://github.com/huggingface/optimum-habana/pull/918 
https://github.com/huggingface/optimum-habana/pull/931
`QUANT_CONFIG=./quantization_config/maxabs_measure_include_outputs.json python  run_generation.py  --model_name_or_path mistralai/Mistral-7B-Instruct-v0.2 --attn_softmax_bf16 --use_hpu_graphs --trim_logits --use_kv_cache --reuse_cache --bf16 --batch_size `
` QUANT_CONFIG=./quantization_config/maxabs_quant.json python run_generation.py --model_name_or_path mistralai/Mistral-7B-Instruct-v0.2 --attn_softmax_bf16 --use_hpu_graphs --trim_logits --use_kv_cache --reuse_cache --bf16 --batch_size 896  --max_new_tokens 128 --max_input_tokens 128 --limit_hpu_graphs`
Throughput (including tokenization) = 13235.770108332108 …
=> Added Mistral fp8 support

examples/text-generation/run_generation.py, examples/text-generation/utils.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
Support for setting fast softmax mode in FusedSDPA operator. This is a tradeoff: performance vs accuracy.
Data on performance:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wszczure/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wszczure/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>
<body link="#0563C1" vlink="#954F72">
Ratio | Max input tokens | Max new tokens | Batch size | Throughput without fast softmax   [tokens/s] | Throughput with fast …
=> Enable fast softmax mode in FusedSDPA

examples/language-modeling/requirements.txt
Fix pytest version in language modelling as a temporary measure untill TF 4.39.
(final fix: https://github.com/huggingface/transformers/pull/29154)
=> Downgrade pytest in language modelling

optimum/habana/transformers/models/mistral/modeling_mistral.py
- Currently Fused SDPA doesn't support fp8,  this PR will enable fp8 also for fusedSDPA. 
- update update_sincos_cache for token exceeding max position embedding size.
Currently FusedSDPA with fp8 with 32k has accuracy issue though.  16k is fine.
=> FP8 FusedSDPA support for Mistral

examples/text-generation/utils.py
torch.compile keep input mutation in graph this avoids unnecessary memcpy coming from inplace index_copy from kv cache
=> torch.compile keep input mutation in graph this avoids unnecessary memcpy

examples/text-generation/README.md
Document FusedScaledDotProductAttention quantization
=>  Document FusedScaledDotProductAttention quantization

optimum/habana/transformers/models/falcon/modeling_falcon.py
This PR follows the change for llama in https://github.com/HabanaAI/optimum-habana-fork/pull/154/files 
This increased the maximum batch size of BF16 falcon180b inference from 250 to 316
updated command (remove --reuse_cache)
python ../gaudi_spawn.py \
--use_deepspeed --world_size 8 run_generation.py \
--model_name_or_path /root/data/falcon/falcon-180b/snapshots/d2ea5531862d4fe907280234990e6380d2befd97/ \
--use_hpu_graphs \
--use_kv_cache \
--bf16 \
--batch_size 316 \
--max_new_tokens 128 \
--max_input_tokens 128 \
--limit_hpu_graphs \
--n_iterations 3 \
--trim_logits \
--bucket_internal \
--bucket_size 128 \
--prompt "I've always managed to dodge the bullet and avoid the addictive pull of Pokemon. Leave it to a button-mashing brawler with plastic figurine accessories to finally get me …
=> Ensure KV cache is not returned as output tensor during decode phase for Falcon

optimum/habana/transformers/trainer.py
Port from https://github.com/huggingface/optimum-habana/pull/992
We have a condition check if the grad_norm tensor is a single element or not. If it's not we convert grad_norm as list.
(https://github.com/huggingface/optimum-habana/pull/938)
But for logging, we don't use grad_norm if it's a list so there's no point to get grad_norm list.
I changed condition to check if grad_norm is a list just assign None.
We see that this list conversion causes a perf issue.
=> Assign grad_norm for logging only if it's a single element tensor

examples/text-generation/run_generation.py
This PR enables by default fast softmax feature of FusedSDPA.
To do that it changes handling of flash attention related arguments inside run_generation.py
Now the flags can also except values such as "--use_flash_attention true/false" etc.
Flag "--flash_attention_fast_softmax" will be true if "--use_flash_attention" is true. It can be explicitly turned off by passing "--flash_attention_fast_softmax false" to the script.
=> Enable fast softmax as default

examples/text-generation/utils.py
the most recent rebase of examples/text-generation/utils.py had removed the host memory improvement of marking only scales as consts. this change brings this code back.
=> fixed wrong OH rebase of examples/text-generation/utils.py

examples/text-generation/README.md, optimum/habana/transformers/models/falcon/modeling_falcon.py
add use_flash_attentiong, flash_attention_recompute, flash_attention_causal_mask add mark step per decoder
add fusedsdpa fp8
fix memory issue
=> Falcon optimization:

examples/summarization/ds_flan_t5_z3_config_bf16.json
When running with torch_compile enabled, a ValueError is seen (as mentioned in title) at the end of training.
Setting this flag to true bypasses the error.
=> Fix for ValueError:Cannot get 16bit model weights because `stage3_gather_16bit_weights_on_model_save` in DeepSpeed config is False

examples/text-generation/README.md, examples/text-generation/run_lm_eval.py
* For Falcon,
- Updated examples/text-generation/README.md to guide the usage of flash attention options.
- Updated run_lm_eval.py to enable flash attention options, and to skip "attn_softmax_bf16" option not supported.
=> Update falcon fp8 flash attention

examples/question-answering/README.md
Added the special env flags and command line arguments needed to enable torch.compile mode for Albert-xxl.
=> Update README for Albert torch.compile mode

optimum/habana/accelerate/utils/transformer_engine.py
hccl gets imported before the env flags are set due an initial transformer_engine import causing following error from bridge
"RuntimeError: collective nonSFG is not supported during hpu graph capturing"
Fixed this by importing TE only for training fp8 use-cases (--fp8 argument set by user).
=> Import TE module conditionally

examples/text-generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
adding recompute as an optional argument in fused_sdpa to avoid the context manager for torch.compile mode since it causes graph break. It also works in lazy mode.
=> avoid context manager in Flash atention for torch.compile

optimum/habana/transformers/models/llama/modeling_llama.py
Currently running fast softmax on decode can cause perf degradation on some configs. Thus this PR turns it off for decode.
Results:
Model | Batch Size | Nodes | Performance with Fast Softmax (Prefill Only) | Performance without Fast Softmax
------|------------|-------|---------------------------------------------|----------------------------------
Llama 2-70B 31744/1024 Tokens | 12 | 8 | 105.27 | 97.08
Llama 2-70B 24576/8192 Tokens | 16 | 8 | 418.95 | 405.55
Llama 2-70B 16384/16384 Tokens | 24 | 8 | 673.99 | 665.84
Llama 2-70B 4096/4096 Tokens | 16 | 2 | 304.17 | 303.75
Llama 2-70B 4096/4096 Tokens | 59 | 4 | 1149.75 | 1147.10
=> Use fast softmax only on prefill

optimum/habana/transformers/generation/utils.py
Currently, bucket_size is only supported for a few models such as llama and falcon. This PR is to add bucket_size support for gpt_bigcode model , this can be useful if the dataset has varying prompt lengths.
=> Add --bucket_size support for gpt_bigcode

examples/text-generation/requirements.txt
added constrain to the datasets version to be installed, as a new version was released and broke llama.
it fixes this error:
<details><summary>Traceback</summary>
<p>
Traceback (most recent call last):
File "/root/optimum-habana-fork/examples/text-generation/run_lm_eval.py", line 194, in <module>
main()
File "/root/optimum-habana-fork/examples/text-generation/run_lm_eval.py", line 162, in main
lm_tasks = lm_eval.tasks.get_task_dict(args.tasks)
File "/usr/local/lib/python3.10/dist-packages/lm_eval/tasks/__init__.py", line 415, in get_task_dict
task_name_dict = {
File "/usr/local/lib/python3.10/dist-packages/lm_eval/tasks/__init__.py", line 416, in <dictcomp>
task_name: get_task(task_name)()
File "/usr/local/lib/python3.10/dist-packages/lm_eval/base.py", line 510, in __init__ …
=> constrain datasets version in requirements.txt

examples/text-generation/run_generation.py, examples/text-generation/utils.py, optimum/habana/transformers/models/mixtral/modeling_mixtral.py
- allows to execute with torch.compile mode for other than Llama model in text-generation example
- makes Mixtral to run mark_step only in case of lazy in order to avoid redundant warnings
=> Allow torch.compile execution for other than Llama text-generation models

optimum/habana/accelerate/accelerator.py
Deepspeed API for enabling torch.compile has changed with latest commits in deepspeed. Instead of configuring it from ds_configuration.json file now it needs to be done post deepspeed.initialize() call. This PR adds the required change to accelerate.py to invoke new torch.compile API if torch_compile_backend is set.
=> Add support to enable torch.compile with Deepspeed

examples/text-generation/utils.py
=> Fix t.compile for Granite20b  

examples/text-generation/run_generation.py
While running the inference with a dataset (ex: Alpaca that has 52000 prompts), executing the full dataset takes longer time. For various experiment purposes running inference with the full dataset is not desirable. Add a command line argument to run the inference with the partial dataset.
Flag ' -- run_partial_dataset' that runs the inference with the dataset for specified --n_iterations(default:5)
=> [SW-191023][PyTorch][Optimum-Habana-fork]: Add flag to run inference with partial dataset

optimum/habana/transformers/generation/utils.py
Move the 1st token finish time to not include 2nd step kv pad time. (PR from OH https://github.com/huggingface/optimum-habana/pull/1091)
Fixes # ([SW-191601](https://jira.habana-labs.com/browse/SW-191601))
=> Move the 1st token finish time to not include 2nd step kv pad time

optimum/habana/transformers/trainer.py
Fix nan eval loss in contrastive-image-text clip-roberta training.
Otherwise, get "losses_host not defined" error
=> Fix nan eval loss in clip training

examples/language-modeling/run_lora_clm.py, optimum/habana/accelerate/utils/transformer_engine.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
This PR enables the usage of Fused Scaled Dot Product Attention in the FP8 version of the LLama model. Tested on LLama finetuning using LoRA. Set the `--flash_attention_fp8` flag to use FusedSDPA.
=> [SW-185803] Enable FusedSDPA fp8 in Llama FT

examples/language-modeling/run_lora_clm.py, optimum/habana/accelerate/utils/transformer_engine.py, optimum/habana/transformers/generation/configuration_utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
This reverts commit 35f6fbe373de8294f4d88d5bd854360ecf99daa2.
=> Revert "[SW-185803] Enable FusedSDPA fp8 in Llama FT (#291)"

optimum/habana/transformers/generation/utils.py
fix data-type mismatch for mlperf_inference accuracy test
=> fix data-type mismatch for mlperf_inference accuracy test

examples/text-generation/run_generation.py, examples/text-generation/utils.py, optimum/habana/distributed/__init__.py, optimum/habana/distributed/serialization.py, optimum/habana/distributed/strategy.py, optimum/habana/distributed/tensorparallel.py, optimum/habana/distributed/tp.py, optimum/habana/distributed/tp_wrapping.py, optimum/habana/transformers/models/llama/modeling_llama.py
Tensor parallel by extending GaudiLlamaAttention -> TPGaudiLlamaAttention  and GaudiLlamaMLP -> TPGaudiLlamaMLP
use parameter --distributed_strategy="tp" to invoke this code path
=> Tensor parallel  distributed strategy without using deepspeed

optimum/habana/transformers/generation/utils.py
=> Don't include padding in first token latency time

examples/text-generation/run_generation.py, examples/text-generation/utils.py
Added new argument --load_cp
Currently llama7b in uint4 is supported
=> Support loading huggingface checkpoint

optimum/habana/transformers/models/mistral/modeling_mistral.py, tests/test_text_generation_example.py
--use_flash_attention was not used for FP8 Mistral due to the accuracy issue (https://github.com/huggingface/optimum-habana/pull/985). Since the accuracy issue is now gone in 1.17.0, this PR refactor the mistral modeling script to enable flash attention for FP8 flow. Also the GaudiMistralAttentionLongSequence class is removed because the model can serve seq_len==max_position_embedding and performs better without it.
For the case with  --batch_size 7 --max_new_tokens 512 --max_input_tokens 32000 
1. Original code without flash attention:
Throughput (including tokenization) = 42.07969811168232 tokens/second
Number of HPU graphs                = 121
Memory allocated                    = 37.51 GB
Max memory allocated                = 94.31 GB
Total memory available              = 94.62 GB …
=> Add flash attention support for FP8 Mistral

examples/text-generation/run_generation.py, optimum/habana/transformers/generation/utils.py, optimum/habana/transformers/models/llama/modeling_llama.py
Valid sequence length (VSL) feature provides a way of indicating to the FusedSDPA operator which part of inputs contain valid information and which are just padding. Thanks to that operator can skip unnecessary computation which improves performance.
This change also enables using "causal" flag for the prefill in case inputs are of different length. Previously using causal with different length of inputs would cause padding to be included in computation which caused degradation in accuracy.
Below is performance data showcasing the improvement in the model with causal flag:
BS - batch size
MIT - max input tokens
MNT - max new tokens
VSL - valid sequence lengths
BF16:
BS | MIT | MNT | Causal - Lower Triangular Softmax (Through VSL Feature) | Throughput (Including Tokenization) Tokens/s | …
=> Support for valid sequence length feature in FusedSDPA for llama

examples/text-generation/run_generation.py, examples/text-generation/utils.py
This adds valid_sequence_lengths tensor to generation_config when the config is initialized as opposed to doing so after the initialization which could cause issues in some flows.
=> Fix missing valid_sequence_lengths tensor from generation_config

examples/text-generation/experimental/run_generation.py, examples/text-generation/experimental/run_lm_eval.py, examples/text-generation/utils.py
This is an experimental change to test Habana's PT2E-quantization flow with LLM, such as Llama2.
Motivation:
PT2-Export based quantization workflow in Pytorch captures the model into a graph and performs quantization transformations on top of the ATen dialect graph. This approach is claimed to have higher model coverage as compared to earlier FX Graph Mode Quantization approach, better programmability, and a simplified UX. But, PT2-Export has limitation that the model must be serialized (without any graph breaks, e.g. no data dependent conditional flow etc.). As a result, very first stage of PT2E quantization flow fails for autoregressive models like Bloom, GPTJ, Llama2. Habana has come up with a promising solution to overcome the above-mentioned problem.
This change includes …
=> Test Habana's PT2E-quantization flow with Llama2

optimum/habana/transformers/generation/utils.py
This PR adds check for existance of valid_sequence_lengths attribute on generation config. Necessary for the cases where setup_generation_config is not called and thus valid_sequence_lengths doesn't exists.
=> Add check for vsl attribute in GaudiGenerationMixin

examples/text-generation/quantization_config/act_maxabs_pow2_weights_pcs_opt_pow2_quant.json, examples/text-generation/quantization_config/maxabs_measure.json, examples/text-generation/quantization_config/maxabs_measure_include_outputs.json, examples/text-generation/quantization_config/maxabs_quant.json, examples/text-generation/quantization_config/maxabs_quant_phi.json, examples/text-generation/quantization_config/unit_scale_quant.json
Remove unnecessary 'allowlist'/'blocklist' configurations as the default configuration is now identical to configuring empty lists
=> Simplify HQT config - Configure default behaviour as empty 'allowlist'/'blocklist' configuration 

examples/text-generation/run_generation.py
When alpaca dataset is used with Llama2 7B fine-tuning in Dynamic mode, the warmup code is not executed. This is because the warmup code is under check 'if prompt_length > 0' and prompt_length is -1 for Dynamic mode. The warmup code is enabled and some prints are added that Nightly Job looks for while parsing.
=> [SW-194967]: Enable warmup steps and log prints for Nightly Job script
