HabanaAI/optimum-habana-fork

- examples/stable-diffusion/train_text_to_image_sdxl.py
> Load unet weight as mixed precision type

- examples/contrastive-image-text/README.md
Fixes the perf regression issue in clip-roberta inference CI by using Habana Dataloader instead.
- [Y] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [Y] Did you make sure to update the documentation with your changes?
- [N] Did you write any new necessary tests?
> Fix inference command clip-roberta

- examples/stable-diffusion/train_text_to_image_sdxl.py
> [UCS-2623] add sdxl profiling

- examples/stable-diffusion/run_8x.sh
- examples/stable-diffusion/train_text_to_image_sdxl.py
Fixed hpu_graphs for inference bug.
Added warmup step in throughput calculation.
> Added warmup step in throughput calculation.

- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/models/llama/modeling_llama.py
Also add clear cache() to save memory.
make style changes also added.
> Further fixes for performance with internal bucketing.

- examples/language-modeling/README.md
Update llama-7b command to include eval
> Update llama-7b command to include eval

- examples/contrastive-image-text/clip_media_pipe.py
Fixes NoneType issue in Clip Media Reader 
- [N] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [N/A] Did you make sure to update the documentation with your changes?
- [N] Did you write any new necessary tests?
> [BridgeTower] Fix for NoneType in clip mediapipe 

- examples/stable-diffusion/run_8x.sh
- examples/stable-diffusion/train_text_to_image_sdxl.py
> Fix 8x run issue. Enable user_hpu_graph_for_training.

- examples/stable-diffusion/run_1x_bs16.sh
- examples/stable-diffusion/train_text_to_image_sdxl.py
> Added logging_step argument to reduce logging time

- optimum/habana/transformers/generation/utils.py
- tests/transformers/tests/generation/test_utils.py
> Fixing tests by making static_shapes False

- examples/language-modeling/run_lora_clm.py
- optimum/habana/transformers/trainer.py
Fixes bug in usage of "use_used_repo" flag.
> Change check to False explicitly for use_fused_rope

- examples/text-generation/README.md
- examples/text-generation/run_generation.py
- examples/text-generation/run_lm_eval.py
- examples/text-generation/utils.py
- optimum/habana/transformers/generation/configuration_utils.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/models/llama/modeling_llama.py
remove depracted kv cache fp8 flag
Change-Id: Id76f94a127dee202376e8f27de7b28f58affedae
> llama fp8 - enable non reuse cache flow for fp8

- examples/language-modeling/run_lora_clm.py
- optimum/habana/transformers/training_args.py
Fix Llama-70B-FSDP model loading issue. 
> Fix Llama-70B-FSDP model loading issue

- examples/text-generation/utils.py
- tests/test_text_generation_example.py
Enable torch_compile mode for distributed
> Enable torch_compile mode for distributed (#659)

- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/models/llama/modeling_llama.py
> Remove usage of clear cache

- examples/text-generation/quantization_config/act_maxabs_hw_weights_pcs_maxabs_pow2_quant.json
- examples/text-generation/quantization_config/maxabs_measure.json
- examples/text-generation/quantization_config/maxabs_quant.json
- examples/text-generation/quantization_config/unit_scale_quant.json
- tests/transformers/tests/test_modeling_common.py
Rename whitelist and blacklist to allowlist and blocklist
> Rename whitelist & blacklist

- examples/speech-recognition/README.md
- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/wav2vec2/__init__.py
- optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
- tests/baselines/wav2vec2_large_lv60.json
Changes to modeling_wav2vec.py required to enable HPU graphs for Wav2Vec2-ASR. This is done to reduce host overhead and make model performance device compute bound.
> Enable hpu graphs for Wav2Vec-ASR fine-tuning

- tests/test_fsdp_examples.py
Clean-up flags from bert-base FSDP flags. 
> Clean-up BERT-BASE FSDP test

- examples/summarization/run_summarization.py
- optimum/habana/transformers/training_args.py
Fix BART inference failure due to attn_implementation initialization to torch sdpa.
> Fix BART inference failure due to attn_implementation initialization

- examples/stable-diffusion/training/README.md
- examples/stable-diffusion/training/gpu/README
- examples/stable-diffusion/training/gpu/default_config_1x.yaml
- examples/stable-diffusion/training/gpu/default_config_8x.yaml
- examples/stable-diffusion/training/gpu/run_fp16.sh
- examples/stable-diffusion/training/gpu/train_text_to_image_sdxl.py
- examples/stable-diffusion/training/gpu/train_text_to_image_sdxl_bf16.py
- examples/stable-diffusion/training/run_1x_gaudi1.sh
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- top commit d83c240bfc5a6ec4ea9c7441164afca9f4f25cd3
> Upmerge dev_ae_stdxl_ft change to habana-main

- optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
Update modeling_wav2vec code to ensure that custom ctc_loss op is chosen only for Gaudi2 and above.
> Run custom ctc_loss only for Gaudi2

- optimum/habana/transformers/trainer.py
This PR add support for warm up steps consideration during inference.
Issue was seen in BERT text classification, the inference perf was unstable between runs in same device.
This PR handles the issue.
JH...!
> Add warmup step feature support for inference

- optimum/habana/accelerate/accelerator.py
- optimum/habana/accelerate/state.py
- optimum/habana/accelerate/utils/__init__.py
- optimum/habana/accelerate/utils/transformer_engine.py
- optimum/habana/peft/layer.py
- optimum/habana/transformers/training_args.py
Integrate Transformer Engine and FP8 in optimum-habana-fork
> Integrate Transformer Engine and FP8 support

- optimum/habana/transformers/models/llama/modeling_llama.py
Added additional check to run with distributed enabled and  world_size=1
> Added additional check to run with distributed enabled and  world_size=1

- examples/text-generation/utils.py
> Fixed const serialization path call to bridge

- examples/stable-diffusion/training/README.md
> sarkar/Update README.md

- examples/text-generation/quantization_config/act_maxabs_pow2_weights_pcs_opt_pow2_quant.json
added a new text-gen quant conf example file with a name that matches its scale method
> new text-gen quant conf file with a name that matches its scale method

- optimum/habana/transformers/models/llama/modeling_llama.py
Currently fp8fsdpa quantization supported only when flash_attention_recompute is True
> enforce recompute flag on fsdpa quantization

- examples/text-generation/run_lm_eval.py
add flash_attention_causal_mask to run_lm_eval.py
> add flash_attention_causal_mask to run_lm_eval.py

- optimum/habana/transformers/models/llama/modeling_llama.py
Update modeling_llama to enable "fast" softmax 
> Update modeling_llama to enable "fast" softmax

- optimum/habana/transformers/generation/configuration_utils.py
> Adding flash_attention_fast_softmax to config utils

- examples/text-generation/run_lm_eval.py
Fixed a bug which adds the "reuse_cache" flag regardless of the model type.
> Fix "reuse_cache" Bug

- optimum/habana/diffusers/pipelines/controlnet/pipeline_controlnet.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_ldm3d.py
- optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
- optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
> Fix throughput calculation for diffusion models (#715)

- optimum/habana/transformers/models/mistral/modeling_mistral.py
Enable HQT matmul fp8 quantization for Mistral Attention layer.
Improves performance (from 11313 samples/s to 12935 for 128x128x bs 896 configuration).
Softmax fp8 quantization doesn't seem to add any performance improvement, but actually slows it down since fused kernel is not being used.
> Add HQT Matmul fp8 support for Mistral

- examples/text-generation/README.md
- examples/text-generation/run_generation.py
- tests/test_text_generation_example.py
> Remove --fp8 flag from script

- examples/text-generation/run_generation.py
> bf16 with disk offload protection

- optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
> Fix RoPE data type issue for StableLM and gpt_neox

- optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
> make style for modeling_gpt_neox

- examples/text-generation/utils.py
Auto-disable hpu_graph for BS1 (latency test)
> Auto-disable hpu_graph for BS1 (latency test)

- examples/text-generation/run_generation.py
> Warn user when using --disk_offload without hqt

- optimum/habana/transformers/trainer.py
> Grad norm tensor fix (#938)

- tests/transformers/tests/models/distilbert/test_modeling_distilbert.py
- tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py
- tests/transformers/tests/models/swin/test_modeling_swin.py
- tests/transformers/tests/models/t5/test_modeling_t5.py
- tests/transformers/tests/models/vit/test_modeling_vit.py
updating optimum-habana-fork model test as per the transformers test suite.
Update has done to t5 and distilBert model as there is some new test case addition.
> Habana fork transformer

- examples/question-answering/README.md
README update for migrating to torch.compile
> BERT training migrated to torch.compile

- optimum/habana/transformers/models/llama/modeling_llama.py
> Adding check for FusedSDPA from TE

- setup.py
> Move pytest dependency (#883)

- optimum/habana/checkpoint_utils.py
prevent out of memory on 8x mixtral eager text-generation
> checkpointing fix for mixtral

- optimum/habana/transformers/models/mistral/modeling_mistral.py
Fix performance issue in mistral
Without this fix, the first token generation will take more time and the performance is bad.
> fix performance issue in mistral

- examples/text-generation/utils.py
fix for selective seq length test with batch size 1
> fix for selective seq length test with batch size 1

- examples/text-generation/quantization_tools/unify_measurements.py
> Update unifier script

- examples/text-generation/utils.py
* reverted wrong OH rebase of utils.py
Change-Id: Ib78e6d4dd407c22ad1863b71554932c6b4f495d8
* reverted mistake in previous commit
Change-Id: If955522a882b7671465d05a22cf6bab05a8e07b0
* fixed extra space
Change-Id: I060e922c0d68fc6b96344b383907d61c24a93067
---------
> fixed wrong OH rebase of examples/text-generation/utils.py

- examples/text-generation/run_generation.py
- examples/text-generation/run_lm_eval.py
- examples/text-generation/utils.py
> Quantize using INC or HQT

- examples/text-generation/utils.py
simplified conditions for hpu graph exclusion with BS1
> simplified conditions for hpu graph exclusion with BS1

- examples/text-generation/quantization_tools/unify_measurements.py
> Unify measurements script to support multi scales on inputs

- optimum/habana/transformers/modeling_utils.py
- optimum/habana/transformers/models/__init__.py
- optimum/habana/transformers/models/falcon/__init__.py
Fixes https://github.com/huggingface/optimum-habana/issues/590 . Cherry-picked from optimum-habana because we need to migrate to new PEFT version to enable Transformer-Engine (TE).  https://jira.habana-labs.com/browse/SW-184826 
> Fix falcon 180b oom issue if peft > 0.6.2 (#895)

- examples/text-generation/run_generation.py
- examples/text-generation/text-generation-pipeline/pipeline.py
- optimum/habana/transformers/generation/utils.py
- optimum/habana/transformers/training_args.py
- optimum/habana/utils.py
Disable shapes in profiling by default
> No shapes in profilings by default

- examples/question-answering/README.md
Updating batch_size information of Albert-XXL in README
Albert-XXL batch_size will be updated to 16 instead of 12
> Updating batch_size of Albert-XXL in README

- examples/text-generation/utils.py
fix for selective seq length tests with batch size 1
> fix for selective seq length tests with batch size 1

- examples/contrastive-image-text/clip_media_pipe.py
Fixes media device name and fw params for media's external reader
- [ N] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ N/A] Did you make sure to update the documentation with your changes?
- [ N] Did you write any new necessary tests?
> [Clip] Update media device

- examples/stable-diffusion/training/media_pipe_imgdir.py
Fixes media device handling for stable diffusion and move reader to external reader op
- [N] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [N/A] Did you make sure to update the documentation with your changes?
- [N] Did you write any new necessary tests?
> [Stable-Diffusion] Update media device handling and move reader to external reader op

- optimum/habana/accelerate/accelerator.py
- optimum/habana/accelerate/utils/dataclasses.py
> Change the device_id for FSDP plugin

- optimum/habana/transformers/models/mistral/modeling_mistral.py
[huggingface#985
](https://github.com/huggingface/optimum-habana/pull/985)
> add long sequence to mistral

- optimum/habana/transformers/models/llama/modeling_llama.py
Changing Functional Linear to torch.nn.Module Linear
> Changing Linear to torch.nn

- examples/language-modeling/README.md
- tests/baselines/llama_7b.json
- tests/test_examples.py
Adding example test case for the combination of Llama2-7B + MPI + LoRA + FP8 precision
> Add a test for llama finetuning with FP8 precision

- optimum/habana/transformers/trainer.py
Handles NaN eval loss values in run_clip.py
> Fix NaN eval loss

- optimum/habana/transformers/models/falcon/modeling_falcon.py
- optimum/habana/transformers/models/llama/modeling_llama.py
This solves torch compile issue related to using self argument in HQT patched module
> Set KV Cache update as static method

- examples/text-generation/utils.py
Now INC will be the default quantization tool, instead of HQT
> Set use_inc to default true

- examples/text-generation/requirements_lm_eval.txt
- examples/text-generation/run_lm_eval.py
fix spawn MP context, limit cpu and download data
> fix spawn MP context, limit cpu and download data

- optimum/habana/transformers/generation/utils.py
fix data-type mismatch for mlperf_inference accuracy test (#296)
> fix data-type mismatch for mlperf_inference accuracy test (#296)

- examples/text-generation/run_generation.py
- examples/text-generation/utils.py
- optimum/habana/distributed/__init__.py
- optimum/habana/distributed/serialization.py
- optimum/habana/distributed/strategy.py
- optimum/habana/distributed/tensorparallel.py
- optimum/habana/distributed/tp.py
- optimum/habana/distributed/tp_wrapping.py
- optimum/habana/transformers/models/llama/modeling_llama.py
* TP reference -  ibm foundation-model-stack
* Code cleanup -removed unused code
> Tensor parallel  distributed strategy without using deepspeed (#280)

- examples/text-generation/run_generation.py
- examples/text-generation/utils.py
Added new argument --load_cp
Currently llama7b in uint4 is supported
> Support loading hugging face checkpoint

- optimum/habana/transformers/models/llama/modeling_llama.py
> reland - use fast softmax only on prefill

- examples/contrastive-image-text/run_bridgetower.py
> Fix bridgetower example

- optimum/habana/distributed/tensorparallel.py
Disable all_reduce torch compile
> Disable all_reduce torch compile

- tests/transformers/tests/models/bridgetower/test_modeling_bridgetower.py
- tests/transformers/tests/models/clip/test_modeling_clip.py
- tests/transformers/tests/models/falcon/test_modeling_falcon.py
- tests/transformers/tests/models/gpt2/test_modeling_gpt2.py
- tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py
- tests/transformers/tests/models/gptj/test_modeling_gptj.py
updating optimum-habana-fork model test as per the transformers test suite.
adding has done for clip, falcon, bridgetower, gpt2, gptj and gptneox test suite as this were not included earlier to optimum-habana-fork branch.
> [SW-183116]- update optimum-habana test as per the transformers-4.40.2

- optimum/habana/transformers/generation/utils.py
use the tensor wrapping a scalar instead of 1-D tensor. this would avoid "one of the tensors on CPU" error.
> To fix CPU tensor issue

- tests/transformers/tests/models/mistral/test_modeling_mistral.py
- tests/transformers/tests/models/mixtral/test_modeling_mixtral.py
- tests/transformers/tests/models/roberta/test_modeling_roberta.py
- tests/transformers/tests/models/swin/test_modeling_swin.py
- tests/transformers/tests/models/t5/test_modeling_t5.py
- tests/transformers/tests/models/vit/test_modeling_vit.py
- tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
updating optimum-habana-fork model test as per the transformers test suite.
adding has done for mistral, mixtral, roberta, swin, t5, vit and wav2vec2  test models.
> [SW-183116]- update optimum-habana test as per transformers-4.40.2

- Makefile
- tests/test_image_to_text_example.py
> Add x2 group tests_image_to_text_example
